### ISSUE TITLE
Option to play more than one video at the same time?

### ISSUE THREAD

**Issue by amanzan** [touchlane/ExoVideoView#1]
Would it be possible to have an option to allow more than one video playing at the same time? I know it could potentially decrease scrolling performance, but if it's 2 or 3 videos, it should not be that bad.

**Comment by olshevski** [comment]
@amanzan I don't really understand the application of this limit. Can you describe what do you need this for?

**Comment by amanzan** [comment]
I have a RecyclerView with several elements, some of them could be videos.

**Comment by olshevski** [comment]
@amanzan But do you need the limit itself, or do you simply want to be able to start playing all videos visible on a screen in RecyclerView (as many as can fit within the screen at once)?

**Comment by amanzan** [comment]
hmm maybe just a limit would be fine, I don't want too many playing at the same time anyway. but also they should play only when they are visible

**Comment by olshevski** [comment]
I gave a thought about the suggestion, and nah, it feels too much of a rare real-life case. You don't often need to watch several videos at once.

Also, I was trying to solve exactly the opposite problem with my implementation, that is to easily manage logic of stopping previously played video without any additional calls and classes as in other similar libraries.

It is technically possible to rewrite this library and add some kind of a managed pool of ExoPlayers, but you probably need to implement this yourself.
